name: Workflow Evento
on:
  push:
    branches: ["main","feature/*"]
    tags:
      - v*
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: echo "Disparou o Evento PUSH c/ branch e tag"
